# 구별 범죄율 분석예제

In [1]:
import pandas as pd 
import numpy as np

In [3]:
crime_Seoul=pd.read_csv('C:/pyy/02. crime_in_Seoul.csv',thousands=',',encoding='euc-kr')
crime_Seoul.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65   1395    477   1355   1170
1   종로서      3      3      6      5    115     98   1070    413   1278   1070
2  남대문서      1      0      6      4     65     46   1153    382    869    794
3  서대문서      2      2      5      4    154    124   1812    738   2056   1711
4   혜화서      3      2      5      4     96     63   1114    424   1015    861

In [4]:
crime_Seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관서명     31 non-null     object
 1   살인 발생   31 non-null     int64
 2   살인 검거   31 non-null     int64
 3   강도 발생   31 non-null     int64
 4   강도 검거   31 non-null     int64
 5   강간 발생   31 non-null     int64
 6   강간 검거   31 non-null     int64
 7   절도 발생   31 non-null     int64
 8   절도 검거   31 non-null     int64
 9   폭력 발생   31 non-null     int64
 10  폭력 검거   31 non-null     int64
dtypes: int64(10), object(1)
memory usage: 2.8+ KB

In [5]:
'''
공공데이터(https://www.data.go.kr/index.do)
에서 받은 경찰철_경찰관서 위치,주소 csv파일을 읽어 
경찰서의 위치 정보를 저장한다
경찰청_경찰관서 위치, 주소_20200409.csv
'''
police_state=pd.read_csv('C:/pyy/경찰청_경찰관서 위치, 주소_20200409 - 복사본.csv',
                        thousands=',',encoding='euc-kr')
police_state.head()

     청      서 지구대파출소         X좌표        Y좌표                     주소
0  강원청  강릉경찰서  강동파출소  128.978300  37.727760  강원도 강릉시 강동면 안인리 764-1
1  강원청  강릉경찰서  강릉경찰서  128.906763  37.768700           강릉시 포남동 1113
2  강원청  강릉경찰서  남부지구대  128.897125  37.748968         강릉시 노암동 715-16
3  강원청  강릉경찰서  동부지구대  128.926315  37.774032          강릉시 송정동 740-3
4  강원청  강릉경찰서  북부지구대  128.875237  37.835265     강릉시 주문진읍 주문리 312-7

In [8]:
# 서울 중부경찰서 정보 조회하기
police_state[police_state['지구대파출소']=='서울중부경찰서']

        청        서   지구대파출소         X좌표        Y좌표            주소
1464  서울청  서울중부경찰서  서울중부경찰서  126.989614  37.563514  중구 저동2가 62-1

In [9]:
# 서울지역 경찰서 정보만 선택하여 저장하기 
police_seoul=police_state[police_state['청']=='서울청']
police_seoul.head()

        청        서   지구대파출소         X좌표        Y좌표             주소
1207  서울청  서울강남경찰서   논현1파출소  127.029316  37.513791  강남구 논현동 58-13
1208  서울청  서울강남경찰서   논현2파출소  127.033875  37.515220  강남구 논현동 89-13
1209  서울청  서울강남경찰서   삼성1파출소  127.060440  37.514852  강남구 삼성동 107-3
1210  서울청  서울강남경찰서   삼성2파출소  127.048063  37.511289  강남구 삼성동 114-6
1211  서울청  서울강남경찰서  서울강남경찰서  127.067177  37.509036    강남구 대치동 998

In [13]:
# 경찰서의 이름을 서울xxx경찰서 형태
# 중부서 -> 서울중부경찰서
# 범죄현황데이터의 경찰서 이름을 police_seoul데이터의 경찰서 이름으로 변경하여 리스트로저장
police_name=[]
for name in crime_Seoul['관서명']:
    police_name.append('서울'+str(name[:-1])+'경찰서')
police_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [16]:
# 경찰서의 주소정보를 리스트로 저장하기 
# police_seoul 데이터 -> 주소정보
# police_name 이용하여 police_seoul 데이터에서 주소값만 
# police_address 리스트에 저장하기

police_address =[]

for name in police_name:
    select_police = police_seoul[police_seoul['지구대파출소']==name]
    print(select_police['주소'])
    police_address.append(select_police.loc[:,'주소'])

police_address

1464    중구 저동2가 62-1
Name: 주소, dtype: object
1439    종로구 경운동 90-18
Name: 주소, dtype: object
1286    중구 남대문로5가 561
Name: 주소, dtype: object
1345    서대문구 미근동 165
Name: 주소, dtype: object
1475    종로구 인의동 48-57
Name: 주소, dtype: object
1421    용산구 원효로1가 12-12
Name: 주소, dtype: object
1377    성북구 삼선동5가 301
Name: 주소, dtype: object
1310    동대문구 청량1리동 229
Name: 주소, dtype: object
1333    마포구 아현동 618-1
Name: 주소, dtype: object
1413    영등포구 당산동3가 2-11
Name: 주소, dtype: object
1366    성동구 행당동 192-8
Name: 주소, dtype: object
1326    동작구 노량진1동 72
Name: 주소, dtype: object
1259    광진구 구의동 254-32
Name: 주소, dtype: object
1353    은평구 녹번동 177-15
Name: 주소, dtype: object
1229    강북구 번1동 415-15
Name: 주소, dtype: object
1282    금천구 신림8동 544
Name: 주소, dtype: object
1460    중랑구 묵2동 249-2
Name: 주소, dtype: object
1211    강남구 대치동 998
Name: 주소, dtype: object
1253    관악구 봉천4동 산177-3
Name: 주소, dtype: object
1242    강서구 화곡6동 980-27
Name: 주소, dtype: object
1222    강동구 성내1동 540-1
Name: 주소, dtype: object
1449    성북구 종암1동 3-1260
Name: 주소, dtype: object
1273    구로구 구로2동 436
Name: 주소, dtype: object
1359    서초구 서초3동 1726
Name: 주소, dtype: object
1402    양천구 신정6동 321
Name: 주소, dtype: object
1388    송파구 가락본동 9
Name: 주소, dtype: object
1297    노원구 하계동 250
Name: 주소, dtype: object
1341    서초구 방배동 455-10
Name: 주소, dtype: object
1431    은평구 불광2동 산24
Name: 주소, dtype: object
1303    도봉구 창4동 17
Name: 주소, dtype: object
1397    강남구 개포동 14
Name: 주소, dtype: object

[1464    중구 저동2가 62-1
 Name: 주소, dtype: object,
 1439    종로구 경운동 90-18
 Name: 주소, dtype: object,
 1286    중구 남대문로5가 561
 Name: 주소, dtype: object,
 1345    서대문구 미근동 165
 Name: 주소, dtype: object,
 1475    종로구 인의동 48-57
 Name: 주소, dtype: object,
 1421    용산구 원효로1가 12-12
 Name: 주소, dtype: object,
 1377    성북구 삼선동5가 301
 Name: 주소, dtype: object,
 1310    동대문구 청량1리동 229
 Name: 주소, dtype: object,
 1333    마포구 아현동 618-1
 Name: 주소, dtype: object,
 1413    영등포구 당산동3가 2-11
 Name: 주소, dtype: object,
 1366    성동구 행당동 192-8
 Name: 주소, dtype: object,
 1326    동작구 노량진1동 72
 Name: 주소, dtype: object,
 1259    광진구 구의동 254-32
 Name: 주소, dtype: object,
 1353    은평구 녹번동 177-15
 Name: 주소, dtype: object,
 1229    강북구 번1동 415-15
 Name: 주소, dtype: object,
 1282    금천구 신림8동 544
 Name: 주소, dtype: object,
 1460    중랑구 묵2동 249-2
 Name: 주소, dtype: object,
 1211    강남구 대치동 998
 Name: 주소, dtype: object,
 1253    관악구 봉천4동 산177-3
 Name: 주소, dtype: object,
 1242    강서구 화곡6동 980-27
 Name: 주소, dtype: object,
 1222    강동구 성내1동 540-1
 Name: 주소, dtype: object,
 1449    성북구 종암1동 3-1260
 Name: 주소, dtype: object,
 1273    구로구 구로2동 436
 Name: 주소, dtype: object,
 1359    서초구 서초3동 1726
 Name: 주소, dtype: object,
 1402    양천구 신정6동 321
 Name: 주소, dtype: object,
 1388    송파구 가락본동 9
 Name: 주소, dtype: object,
 1297    노원구 하계동 250
 Name: 주소, dtype: object,
 1341    서초구 방배동 455-10
 Name: 주소, dtype: object,
 1431    은평구 불광2동 산24
 Name: 주소, dtype: object,
 1303    도봉구 창4동 17
 Name: 주소, dtype: object,
 1397    강남구 개포동 14
 Name: 주소, dtype: object]

In [17]:
# police_address 값을 이용하여 구이름을 저장하기
gu_name = []

for name in police_address:
    tmp=name.str.split()
    tmp=tmp.tolist()
    tmp_gu=tmp[0]
    gu_name.append(tmp_gu[0])

gu_name

['중구',
 '종로구',
 '중구',
 '서대문구',
 '종로구',
 '용산구',
 '성북구',
 '동대문구',
 '마포구',
 '영등포구',
 '성동구',
 '동작구',
 '광진구',
 '은평구',
 '강북구',
 '금천구',
 '중랑구',
 '강남구',
 '관악구',
 '강서구',
 '강동구',
 '성북구',
 '구로구',
 '서초구',
 '양천구',
 '송파구',
 '노원구',
 '서초구',
 '은평구',
 '도봉구',
 '강남구']

In [18]:
# crime_Seoul 데이터에 구별 컬럼을 추가하기
crime_Seoul.head()
crime_Seoul['구별']=gu_name
crime_Seoul.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [21]:
# 구별 범죄건수들의 합계구하기
crime_Seoul.groupby('구별').sum()

crime_sum=pd.pivot_table(crime_Seoul, index='구별',
                        aggfunc=np.sum)
crime_sum

      강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구     349    449     18     21     10     13   1650   3850   3705   4284
강동구     123    156      8      6      3      4    789   2366   2248   2712
강북구     126    153     13     14      8      7    618   1434   2348   2649
강서구     191    262     13     13      8      7   1260   2096   2718   3207
관악구     221    320     14     12      8      9    827   2706   2642   3298
광진구     220    240     26     14      4      4   1277   3026   2180   2625
구로구     164    281     11     15      6      8    889   2335   2432   3007
금천구     122    151      6      6      4      3    888   1567   1776   2054
노원구     121    197      7      7     10     10    801   2193   2329   2723
도봉구     106    102     10      9      3      3    478   1063   1303   1487
동대문구    146    173     13     13      5      5    814   1981   2227   2548
동작구     139    285      5      9      5      5    661   1865   1587   1910
마포구     247    294     10     14      8      8    813   2555   2519   2983
서대문구    124    154      4      5      2      2    738   1812   1711   2056
서초구     249    393      6      9      6      8   1091   2635   2098   2399
성동구     119    126      8      9      4      4    597   1607   1395   1612
성북구     124    150      4      5      5      5    741   1785   1855   2209
송파구     178    220     10     13     10     11   1129   3239   2786   3295
양천구     105    120      3      6      5      3    672   1890   2030   2509
영등포구    183    295     20     22     12     14    978   2964   2961   3572
용산구     173    194     14     14      5      5    587   1557   1704   2050
은평구     141    166      6      9      3      3    711   1914   2306   2653
종로구     161    211      9     11      5      6    837   2184   1931   2293
중구      111    170      6      9      2      3    859   2548   1964   2224
중랑구     148    187      9     11     12     13    829   2135   2407   2847

In [23]:
# 강간, 강도, 살인, 절도, 폭력
# 검거율 컬럼 추가하기
# 검거율 = 검거/발생 *100
# 각각 범죄에 대한 검거율 컬럼 추가하기
# 검거수 컬럼들은 제거하기

crime_sum['강간검거율']=crime_sum['강간 검거']/crime_sum['강간 발생']*100
crime_sum['강도검거율']=crime_sum['강도 검거']/crime_sum['강도 발생']*100
crime_sum['살인검거율']=crime_sum['살인 검거']/crime_sum['살인 발생']*100
crime_sum['절도검거율']=crime_sum['절도 검거']/crime_sum['절도 발생']*100
crime_sum['폭력검거율']=crime_sum['폭력 검거']/crime_sum['폭력 발생']*100
crime_sum.head()

,강간 검거,강간 발생,강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,,,,,
강남구,349,449,18,21,10,13,1650,3850,3705,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,123,156,8,6,3,4,789,2366,2248,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,126,153,13,14,8,7,618,1434,2348,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,191,262,13,13,8,7,1260,2096,2718,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,221,320,14,12,8,9,827,2706,2642,3298,69.062500,116.666667,88.888889,30.561715,80.109157

In [27]:
del crime_sum['강간 검거']
del crime_sum['강도 검거']
del crime_sum['살인 검거']
del crime_sum['절도 검거']
del crime_sum['폭력 검거']

KeyError: '강간 검거'

In [28]:
crime_sum[['살인 발생','살인검거율']].head()

     살인 발생       살인검거율
구별
강남구     13   76.923077
강동구      4   75.000000
강북구      7  114.285714
강서구      7  114.285714
관악구      9   88.888889

In [29]:
#검거율 데이터 중 100보다 큰값은 100으로 변경하기 
col_list= ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']

for column in col_list:
    crime_sum.loc[crime_sum[column]>100, '강간검거율']=100

crime_sum.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,100.000000,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,100.000000,92.857143,114.285714,43.096234,88.637222
강서구,262,13,7,2096,3207,100.000000,100.000000,114.285714,60.114504,84.752105
관악구,320,12,9,2706,3298,100.000000,116.666667,88.888889,30.561715,80.109157

In [30]:
# **발생 컬럼명을 **으로 바꾸기
crime_sum.rename(columns={'강간 발생':'강간','강도 발생':'강도',
                         '살인 발생':'살인','절도 발생':'절도',
                         '폭력 발생':'폭력'},inplace=True)
crime_sum.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,100.000000,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,100.000000,92.857143,114.285714,43.096234,88.637222
강서구,262,13,7,2096,3207,100.000000,100.000000,114.285714,60.114504,84.752105
관악구,320,12,9,2706,3298,100.000000,116.666667,88.888889,30.561715,80.109157

In [31]:
# 범죄값들을 정규화 하기
# 기본적인 머신기능 모듈
from sklearn import preprocessing

In [32]:
col=['강간','강도','살인','절도','폭력']
x=crime_sum[col].values
# 정규식
# MinMaxScaler() 0~1사이의 값으로 정규화 
min_max_scaler = preprocessing.MinMaxScaler()

x_scaled = min_max_scaler.fit_transform(x.astype(float))
crime_norm=pd.DataFrame(x_scaled, columns=col,
                       index=crime_sum.index)
crime_norm

            강간        강도        살인        절도        폭력
구별
강남구   1.000000  0.941176  0.916667  1.000000  1.000000
강동구   0.155620  0.058824  0.166667  0.467528  0.437969
강북구   0.146974  0.529412  0.416667  0.133118  0.415445
강서구   0.461095  0.470588  0.416667  0.370649  0.614945
관악구   0.628242  0.411765  0.583333  0.589523  0.647479
광진구   0.397695  0.529412  0.166667  0.704342  0.406864
구로구   0.515850  0.588235  0.500000  0.456405  0.543439
금천구   0.141210  0.058824  0.083333  0.180840  0.202717
노원구   0.273775  0.117647  0.666667  0.405454  0.441902
도봉구   0.000000  0.235294  0.083333  0.000000  0.000000
동대문구  0.204611  0.470588  0.250000  0.329386  0.379335
동작구   0.527378  0.235294  0.250000  0.287765  0.151233
마포구   0.553314  0.529412  0.500000  0.535343  0.534859
서대문구  0.149856  0.000000  0.000000  0.268748  0.203432
서초구   0.838617  0.235294  0.500000  0.564047  0.326064
성동구   0.069164  0.235294  0.166667  0.195192  0.044691
성북구   0.138329  0.000000  0.250000  0.259060  0.258134
송파구   0.340058  0.470588  0.750000  0.780768  0.646407
양천구   0.051873  0.058824  0.083333  0.296735  0.365391
영등포구  0.556196  1.000000  1.000000  0.682095  0.745442
용산구   0.265130  0.529412  0.250000  0.177252  0.201287
은평구   0.184438  0.235294  0.083333  0.305346  0.416875
종로구   0.314121  0.352941  0.333333  0.402225  0.288166
중구    0.195965  0.235294  0.083333  0.532831  0.263497
중랑구   0.244957  0.352941  0.916667  0.384643  0.486235